name: VeldoryaDiscord
version: '1.0.6'
main: com.kardasland.veldoryadiscord.VeldoryaJDA
api-version: 1.16
website: www.kardasland.com
libraries:
  - net.dv8tion:JDA:5.0.0-beta.1
  - mysql:mysql-connector-java:8.0.30
  - com.zaxxer:HikariCP:4.0.3
commands:
  dogrula:
    aliases:
      - verify
      - hesapeşle
      - doğrula
      - esle
      - eşle
  oneri:
    aliases:
      - öneri
      - suggestion
      - suggest
  veldoryadiscord:
    aliases:
      - vdiscord
  dinfo:

  unlink:
    aliases:
      - dogrulamayikaldir
      - eslekaldir
      - eslemeyikaldir