name: VeldoryaDiscord
version: '1.0'
main: com.kardasland.veldoryadiscord.VeldoryaJDA
api-version: 1.16
website: www.veldorya.com
commands:
  dogrula:
    aliases:
      - verify
      - doğrula
  oneri:
    aliases:
      - öneri
      - suggestion
      - suggest
  veldoryadiscord:
    aliases:
      - vdiscord